### ISSUE TITLE
Missing `FetchToken` value for `UniversalEvents` plugin after initial create

### ISSUE THREAD

**Issue by austin94** [fusionjs/create-fusion-app#14]
## Description

After performing a fresh `yarn create fusion-app example` and running `yarn dev`, it looks like `UniversalEvents` plugin requires `FetchToken` to be registered.

<img width="911" alt="screen shot 2018-06-27 at 5 00 45 pm" src="https://user-images.githubusercontent.com/4030377/42006342-19bd1be4-7a2e-11e8-905e-df2b2e64d598.png">

## Suggested Fix

In the other examples it looks like `FetchToken` is registered with [unfetch](https://www.npmjs.com/package/unfetch).

```js
import { FetchToken } from 'fusion-tokens';
import fetch from 'unfetch';

__BROWSER__ && app.register(FetchToken, fetch);
```

If this is a valid fix I'm willing to open a quick PR for this.

Thanks!

**Comment by KevinGrandon** [comment]
Thanks for filing this issue. I believe that for this simple application we actually don't need `UniversalEvents` as it should now be optional for the renderer. Since it's optional, my preference would be to just remove that module from manifests and the code. 

If you're open to submitting a PR, that would be great!
