### ISSUE TITLE
Why do component's render methods get executed twice?

### ISSUE THREAD

**Issue by matthewharwood** [fusionjs/create-fusion-app#67]
Question: I scaffolded a FusionApp using yarn create fusion-app and uber-web scaffold  and  when I render a component the component's render method gets called twice, why is that?  

main.js
  ```
// @flow
import App from 'fusion-react';

import root from './root.js';

export default () => {
  const app = new App(root);
  return app;
};

```
root.js
  ```
// @flow
import React from 'react';
import Home from './pages/home.js';

const root = (
  <Home />
);

export default root;

```
pages/home.js
```

import React from 'react';

let counter = 0;
const Home = () => {
  console.log(counter++);
  return (
    <h1>hello</h1>
  )
}

export default Home;
```

I can do the same thing on CRA or Next and it only executes once.  Maybe it's ssr?

**Comment by KevinGrandon** [comment]
Hello, are you seeing this in the server, or browser or both? Fusion.js is fundamentally different than CRA due to the SSR support. This provides a lot of benefits in some cases, but also has some shortcomings. One such shortcoming was the lack of async rendering/suspense when we first built Fusion.js. This results in the occasional double render.

We're hoping to fix this once React suspense comes out, but unfortunately in the meantime there's not a whole lot we can do about this. Hopefully soon though.
